require(pacman)
p_load(pacman, tidyr, dplyr, shiny, ggplot2, ggthemes, GGally, ggvis, httr,
       lubridate, rmarkdown, stringr)
p_load(psych)
p_load(rio)
#install.packages('arules')
#unloadNamespace("arules")
#update.packages("arules")
library(arules)
library(arulesViz)
p_load(plyr)
titanic <- import("C://Users//ARAD//Desktop//Data science//Salford//handouts//data mining//ASDM//w3//titanic.csv")
View(titanic)
dim(titanic)
names(titanic)
head(titanic)
summary(titanic)
describe(titanic)
str(titanic)
one <- colSums(titanic== 1)
zero<- colSums(titanic==0)
two<- colSums(titanic==2)
three<- colSums(titanic==3)
tot<- rbind(three, two,one, zero)
barplot(tot, legend.text = T, col=rainbow(4))
for (i in colnames(titanic)){ titanic[[i]]<- as.factor(titanic[[i]])}
rules <- apriori(titanic, appearance = list(rhs=c('Survived=0')))
inspect(rules)
plot(rules)
plot(rules, method='grouped')
plotly_arules(rules)
# it seems most of the adult men from third class did not survived
